version: '3'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  websockets:
    build:
      context: ./backend
    command: daphne -b 0.0.0.0  -p 8080 backend.asgi:application
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend
    depends_on:
      - backend
      - websockets
      - frontend
volumes:
  react_build: